### ISSUE TITLE
Team endpoint removed

### ISSUE THREAD

**Issue by petrleocompel** [nicklayb/alfred-bitbucket#35]
I am getting 404 error on listing.

First request i see down is listing teams and on bitbucket it is deprecated
https://developer.atlassian.com/cloud/bitbucket/rest/api-group-teams/#api-teams-get

```
[11:18:38.627] ERROR: BitBucket[Script Filter] Code 1: {
	"items": [
		{
			"title": "HTTPError: Response code 404 (Not Found)\n    at Object.<anonymous> (/*lib/node_modules/alfred-bitbucket/node_modules/got/source/as-promise.js:74:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
			"subtitle": "Press ⌘L to see the full error and ⌘C to copy it.",
			"valid": false,
			"text": {
				"copy": "```\nHTTPError: Response code 404 (Not Found)\n    at Object.<anonymous> (/*/lib/node_modules/alfred-bitbucket/node_modules/got/source/as-promise.js:74:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n```\n\n-\nBitBucket 1.5.1\nAlfred 4.6.2\ndarwin 21.3.0",
				"largetype": "HTTPError: Response code 404 (Not Found)\n    at Object.<anonymous> (/*/lib/node_modules/alfred-bitbucket/node_modules/got/source/as-promise.js:74:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
			},
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			}
		}
	]
}
```

**Comment by petrleocompel** [comment]
Easiest current fix for me is in `teamsService` replace `url` and `map` functions
```javascript
const url = (host) => host + "workspaces/";

const map = ({ type, name, slug }) => {
  const getIcon = () => {
    switch (type) {
      case "user":
        return "👤";
      default:
        return "👥";
    }
  };
  const getTitle = () =>
    [getIcon(), isDefault(slug) ? "🌟" : "", name]
      .filter((emoji) => !!emoji)
      .join("");
  return {
    title: getTitle(),
    subtitle: slug,
    arg: slug,
  };
};
```

**Comment by petrleocompel** [comment]
Sadly I migrated to `Raycast` and I don't need this extension. Just leaving this here if anybody will fix it one day.
